a="Python Programming"
print(a.lower())
print(a.upper())
print(a.title())
print(a.capitalize())
print(a.isdigit())
print(a.isalpha())
print(a.isalnum())
print(a.index('o'))
print(a.count('p'))
print(a.split())
a="python"
print(a)
print(a.strip())
print(a.lstrip())
print(a.rstrip())
print(a.replace("py","java"))
